import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/pages/api/auth/[...nextauth]";
import { SessionProvider } from "next-auth/react";
import Login from "./Login";
import Home from "./page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getServerSession(authOptions)
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
        {
          !session?(
            <Login/>
          ):(
            <Home/>
          )
        }
        </SessionProvider>
        </body>
    </html>
  );
}
